export const data = {
  "key": "v-583cf311",
  "path": "/code/python/python-exception.html",
  "title": "8.1 异常处理",
  "lang": "zh-CN",
  "frontmatter": {
    "category": [
      "Python"
    ],
    "summary": "8.1 异常处理 错误 Error 逻辑错误：算法写错了，例如加法写成了减法 笔误：例如变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去。 例如open函数",
    "head": [
      [
        "meta",
        {
          "property": "og:url",
          "content": "https://clay-wangzhi.com/code/python/python-exception.html"
        }
      ],
      [
        "meta",
        {
          "property": "og:site_name",
          "content": "SRE运维进阶之路"
        }
      ],
      [
        "meta",
        {
          "property": "og:title",
          "content": "8.1 异常处理"
        }
      ],
      [
        "meta",
        {
          "property": "og:type",
          "content": "article"
        }
      ],
      [
        "meta",
        {
          "property": "og:updated_time",
          "content": "2021-09-19T08:54:09.000Z"
        }
      ],
      [
        "meta",
        {
          "property": "og:locale",
          "content": "zh-CN"
        }
      ],
      [
        "meta",
        {
          "property": "article:modified_time",
          "content": "2021-09-19T08:54:09.000Z"
        }
      ]
    ]
  },
  "excerpt": "",
  "headers": [
    {
      "level": 2,
      "title": "产生异常",
      "slug": "产生异常",
      "children": []
    },
    {
      "level": 2,
      "title": "异常的捕获",
      "slug": "异常的捕获",
      "children": []
    },
    {
      "level": 2,
      "title": "异常类及继承层次",
      "slug": "异常类及继承层次",
      "children": []
    },
    {
      "level": 2,
      "title": "BaseException 及子类",
      "slug": "baseexception-及子类",
      "children": [
        {
          "level": 3,
          "title": "BaseException",
          "slug": "baseexception",
          "children": []
        },
        {
          "level": 3,
          "title": "SystemExit",
          "slug": "systemexit",
          "children": []
        },
        {
          "level": 3,
          "title": "KeyboardInterrupt",
          "slug": "keyboardinterrupt",
          "children": []
        }
      ]
    },
    {
      "level": 2,
      "title": "Exception及子类",
      "slug": "exception及子类",
      "children": []
    },
    {
      "level": 2,
      "title": "多种捕获",
      "slug": "多种捕获",
      "children": []
    },
    {
      "level": 2,
      "title": "as 子句",
      "slug": "as-子句",
      "children": []
    },
    {
      "level": 2,
      "title": "finally子句",
      "slug": "finally子句",
      "children": []
    },
    {
      "level": 2,
      "title": "else 子句",
      "slug": "else-子句",
      "children": []
    },
    {
      "level": 2,
      "title": "总结",
      "slug": "总结",
      "children": []
    }
  ],
  "git": {
    "createdTime": 1632041649000,
    "updatedTime": 1632041649000,
    "contributors": [
      {
        "name": "clay-wangzhi",
        "email": "clay.wangzhi@gmail.com",
        "commits": 1
      }
    ]
  },
  "readingTime": {
    "minutes": 6.71,
    "words": 2013
  },
  "filePathRelative": "code/python/python-exception.md"
}
